senders:
  - mail: emailsenderexpriments@gmail.com
    pass: izptigbofjxrlspo

receivers:
  - alberto.mancino@poliba.it
  - a.difazio@studenti.poliba.it
  - antonio.ferrara@poliba.it

messages:
  ok:
    subject: Esperimento LHider terminato
    body: L'esperimento di LHider è terminato con successo
  error:
    subject: Esperimento LHider fallito
    body: L'esperimento di LHider è terminato con un errore
